name: Reusable unit tests

on:
  workflow_call:
    inputs:
      python_versions:
        required: false
        type: string
        default: '["3.9"]'
      coverage:
        required: false
        type: boolean
      pytest_args:
        required: false
        type: string
        default: ''
    secrets:
      CODECOV_TOKEN:
        description: 'Codecov token for coverage (required if coverage is true)'
        required: false

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: ${{ fromJSON(inputs.python_versions) }}

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Poetry
        uses: snok/install-poetry@v1.3
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true
          virtualenvs-path: .venv
      - name: Cache Poetry virtualenv
        uses: actions/cache@v2
        env:
          cache-name: venv-cache
        with:
          path: .venv
          key: venv-${{ matrix.python-version }}-${{ hashFiles('poetry.lock') }}
          restore-keys: |
            venv-${{ matrix.python-version }}-${{ hashFiles('poetry.lock') }}
            venv-${{ matrix.python-version }}-
      - name: Install dependencies
        run: |
          poetry install -v
      - name: Pre-commit checks
        run: |
          poetry run pre-commit run --all-files
      - name: Test with pytest
        env:
          COVERAGE_ARGS: ${{ fromJSON('["--cov-report=xml:.coverage.xml", ""]')[inputs.coverage] }}
          EXTRA_ARGS: ${{ inputs.pytest_args }}
        run: |
          poetry run py.test $COVERAGE_ARGS $EXTRA_ARGS
      - name: Upload coverage to codecov
        uses: codecov/codecov-action@v2
        if: ${{ inputs.coverage }}
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./.coverage.xml
          fail_ci_if_error: true
          verbose: true
